- name: Publish Aptly Mirror
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - artifacting-vars.yml
    - aptly-skip-vars.yml
    - aptly-vars.yml
  become_user: aptly
  become: True
  become_method: sudo
  tasks:
    - assert:
        that:
          - artifacts_version is defined
          - distribution_release is defined
        msg: You need to define what you are releasing!
    - name: Merge the snapshots together
      shell: "aptly snapshot merge miko-{{ artifacts_version }}-{{ distribution_release }} {{ aptly_miko_mapping.get(distribution_release) | join(' ') }}"
      register: aptly_snapshot_merge_create
      when: (aptly_snapshot_merge | default(True)) | bool
      failed_when: aptly_snapshot_merge_create.rc != 0 and aptly_snapshot_merge_create.stderr.find('already exists') == -1
      changed_when: aptly_snapshot_merge_create.stderr.find('already exists') == -1
      tags:
        - aptly_snapshot_merge
        - aptly_snapshot
    - name: Publish snapshot into public/integrated/ folder
      shell: 'aptly publish snapshot -distribution="{{ distribution_release }}" -component="{{ artifacts_version }}" miko-{{ artifacts_version }}-{{ distribution_release }} integrated'
      register: aptly_snapshot_publish
      failed_when: aptly_snapshot_publish.rc != 0 and aptly_snapshot_publish.stderr.find('already used') == -1
      changed_when: aptly_snapshot_publish.stderr.find('already used') == -1
      when: (aptly_snapshot_merge | default(True)) | bool
      tags:
        - aptly_publish
    - name: Publish snapshot into public folder (no merge)
      shell: 'aptly publish snapshot -distribution="{{ distribution_release }}" -component="{{ artifacts_version }}" {{ item }} independant/{{ item }}'
      with_items: "{{ aptly_miko_mapping.get(distribution_release) }}"
      when: not (aptly_snapshot_merge | default(True)) | bool
      tags:
        - aptly_publish
