- name: Publish Aptly Mirror
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - artifacting-vars.yml
    - aptly-skip-vars.yml
    - aptly-vars.yml
  become_user: aptly
  become: True
  become_method: sudo
  tasks:
    - assert:
        that:
          - artifacts_version is defined
          - distribution_release is defined
        msg: You need to define what you are releasing!
    - name: Merge the snapshots together
      shell: "aptly snapshot merge miko-{{ artifacts_version }}-{{ distribution_release }} {{ aptly_miko_mapping.get(distribution_release) | join(' ') }}"
      when: (aptly_snapshot_merge | default(True)) | bool
      tags:
        - aptly_snapshot_merge
        - aptly_snapshot
    - name: Publish snapshot into public folder
      shell: 'aptly publish snapshot -distribution="{{ distribution_release }}" miko-{{ artifacts_version }}-{{ distribution_release }} {{ artifacts_version }}'
      when: (aptly_snapshot_merge | default(True)) | bool
      tags:
        - aptly_publish
    - name: Publish snapshot into public folder (no merge)
      shell: 'aptly publish snapshot -distribution="{{ distribution_release }}" {{ item }} {{ item }}/{{ artifacts_version }}'
      with_items: "{{ aptly_miko_mapping.get(distribution_release) }}"
      when: not (aptly_snapshot_merge | default(True)) | bool
      tags:
        - aptly_publish
