---
- name: Fetches files for rackspace mirror that aren't pip/apt/containers
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - artifacting-vars.yml
  vars:
    artifacts_extradownloads_clone_this_first:
      - repo: "https://github.com/openstack/openstack-ansible-os_swift.git"
        dest: "{{ ansible_roles_folder }}/os_swift"
        version: "{{ roles_details | selectattr('name','equalto', 'os_swift') | list | map(attribute='version') | list }}"
      - repo: "https://github.com/openstack/openstack-ansible-os_tempest.git"
        dest: "{{ ansible_roles_folder }}/os_tempest"
        version: "{{ roles_details | selectattr('name','equalto', 'os_tempest') | list | map(attribute='version') | list }}"
  tasks:
    - name: Fetch roles to find what to download
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version | default('master') }}"
      with_items: "{{ artifacts_extradownloads_clone_this_first }}"
      register: git_clone
      until: git_clone | success
      retries: 2
      delay: 5
    - include_vars: "{{ item }}"
      with_items:
        - "{{ ansible_roles_folder }}/os_swift/defaults/main.yml" 
        - "{{ ansible_roles_folder }}/os_tempest/defaults/main.yml" 
    - name: Ensuring we can store the downloads
      file:
        path: "{{ artifact_extradownloads_dest_folder }}"
        state: directory
    - name: Fetch now
      get_url:
        url: "{{ item.url }}"
        dest: "{{ artifact_extradownloads_dest_folder }}"
        checksum: "{{ item.checksum | default(omit) }}"
      register: fetched_links
      until: fetched_links|success
      retries: 5
      delay: 5
      with_items:
        - url: "{{ swift_pypy_archive.url }}"
          checksum: "sha256:{{ swift_pypy_archive.sha256 }}"
        - url: "{{ tempest_img_url }}"
          checksum: "sha256:{{ tempest_images.0.sha256 }}"
