- name: Sync with mirror
  hosts: mirrors
  vars_files:
    - artifacting-vars.yml
    - aptly-vars.yml
  tasks:
    - name: Synchronize cache
      synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        delete: "{{ item.delete | default(omit) }}"
        recursive: "{{ item.recursive | default(omit) }}"
        owner: "{{ item.owner | default(omit) }}"
      #delegate_to: aptly_cache[0]
      register: synchronize
      until: synchronize|success
      retries: 5
      delay: 5
      failed_when: false
      when: item.action == action
      with_items:
        - action: "pull-all"
          mode: "pull"
          src: "{{ artifacts_root_folder }}"
          dest: "{{ artifacts_root_folder | dirname }}"
          delete: "yes"
          recursive: "yes"
        - action: "push-aptly"
          mode: "push"
          src: "{{ aptly_user_home }}"
          dest: "{{ artifacts_aptrepos_dest_folder | dirname }}"
    - name: Make sure pulled data has the proper permissions
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        recurse: "{{ item.recurse | default(omit) }}"
        owner: "{{ item.owner | default(omit) }}"
      when: item.action == action
      with_items:
        - path: "{{ aptly_user_home }}"
          state: "directory"
          recurse: "yes"
          owner: "{{ aptly_user }}"
          action: "pull-all"
        - path: "{{ aptly_user_home }}"
          state: "directory"
          recurse: "yes"
          owner: "root"
          action: "push-aptly"
