---
# Copyright 2014-2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: aptly-install-and-mirror.yml
  vars:
    aptly_mirror_do_updates: "False"



- name: Pull apt artifacts from rpc-repo
  hosts: mirrors
  vars_files:
    - aptly-vars.yml
  tags:
    - pull_from_mirror
  tasks:
    - name: Synchronize artifacts
      synchronize:
        src: "{{ aptly_user_home }}"
        dest: "{{ artifacts_aptrepos_dest_folder | dirname }}"
        mode: pull
        delete: yes
        rsync_opts:
          - "--quiet"
          - "--stats"
          - "--log-file='/var/log/rpc-repo.log'"
          - "--chown='{{ webservice_owner }}:www-data'"
      register: synchronize
      until: synchronize | success
      retries: 5
      delay: 5
      when: "{{ lookup('ENV','PULL_FROM_MIRROR') | bool }}"



- include: aptly-install-and-mirror.yml
  vars:
    aptly_mirror_do_updates: "True"



- name: Create/publish snapshot(s) for the release
  hosts: localhost
  connection: local
  gather_facts: no
  become_user: aptly
  become: True
  become_method: sudo
  vars_files:
    - aptly-vars.yml
  tasks:

    - include: aptly-snapshot-create.yml
      with_items: "{{ aptly_miko_mapping[rpc_series].keys() }}"
      loop_control:
        loop_var: distribution_release
      tags:
        - aptly_snapshot_create

    - include: aptly-snapshot-publish.yml
      when: "{{ lookup('ENV','PUBLISH_SNAPSHOT') | bool }}"
      with_items: "{{ aptly_miko_mapping[rpc_series].keys() }}"
      loop_control:
        loop_var: distribution_release
      tags:
        - aptly_snapshot_publish

    - name: 'Clean aptly database'
      command: 'aptly db cleanup'
      tags:
        - aptly_db_cleanup



- name: Push apt artifacts to rpc-repo
  hosts: mirrors
  vars_files:
    - aptly-vars.yml
  tags:
    - push_to_mirror
  tasks:
    - name: Ensure the folders are present on the repo before we try to sync them
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ webservice_owner }}"
        group: "www-data"
      with_items:
        - "{{ aptly_user_home }}"
        - "{{ artifacts_root_folder }}"
      when: "{{ lookup('ENV','PUSH_TO_MIRROR') | bool }}"

    - name: Synchronize artifacts
      synchronize:
        src: "{{ aptly_user_home }}"
        dest: "{{ artifacts_aptrepos_dest_folder | dirname }}"
        mode: push
        delete: yes
        rsync_opts:
          - "--quiet"
          - "--stats"
          - "--log-file='/var/log/rpc-repo.log'"
          - "--chown='{{ webservice_owner }}:www-data'"
      register: synchronize
      until: synchronize | success
      retries: 5
      delay: 5
      when: "{{ lookup('ENV','PUSH_TO_MIRROR') | bool }}"

    - name: Sync apt public key with mirror
      copy:
        src: "{{ aptly_custom_gpg_pubkey_file }}"
        dest: "{{ aptly_custom_gpg_pubkey_file }}"
        owner: "{{ webservice_owner }}"
        group: "www-data"
      when: "{{ lookup('ENV','PUSH_TO_MIRROR') | bool }}"
